version: '3.9'
services:
  gwservice:
    image: kds.inveniacorp.com/dev/gw-service/gw-service:latest
    networks:
      - msa
    ports:
      - "8011:8011"
    environment:
      TZ: "Asia/Seoul"
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: "8011"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_URI: "http://configserver:8888"
      ENCRYPT_KEY: "damu"
networks:
  msa:
    external: true
    name: msa
