# Default settings
server:
  port: 8011

spring:
  mvc:
    servlet:
      path: /gw-service/v1
  config:
    import: "optional:configserver:http://configserver:8888"
  application:
    name: gw-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: admin
    password: inveni@2021
  cloud:
    inetutils:
      ignored-interfaces:
        - eth0*
        - eth2*
    config:
      fail-fast: true # 실패시 재시도
      discovery:
        enabled: true # 유레카에서 검색
  datasource:
    hikari:
      connection-test-query: "SELECT * FROM IPLIST" # JDBC 4.0 미지원으로 인해 강제 변경
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sso.inveniacorp.com/auth/realms/service
          jwk-set-uri: https://sso.inveniacorp.com/auth/realms/service/protocol/openid-connect/certs

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.invenia.gwservice
  mapper-locations: mybatis/mapper/**/*.xml

management:
  endpoint:
    health:
      show-details: always # actuator에서 디테일한 정보들을 확인하기 위해 설정
  health:
    diskspace:
      enabled: true

eureka:
  client:
    registerWithEureka: true # 유레카에 서비스 등록
    fetchRegistry: true # 레지스트리 사본을 로컬로 캐시한다
    serviceUrl:
      defaultZone: ${EUREKASERVER_URI:http://localhost:8761/eureka} # 유레카 서비스 위치

logging:
  level:
    reactor:
      netty:
        http:
          client:
            HttpClient: DEBUG
    org:
      springframework:
        security: DEBUG

destinations:
  topics:
    notify:
      exchange: notify

---
# Test settings
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: "jdbc:Altibase://100.100.10.72:10003/mydb"
    driver-class-name: "Altibase.jdbc.driver.AltibaseDriver"
    username: "g2"
    password: "{cipher}8437ea7b287ebba1eea255d24edf2164a27e1d7bb7882cddecf40c7fea4720ec"
